insert into public.puzzle_bank (
  slug,
  fen,
  motif_json,
  nlp_prompt,
  input_placeholder,
  subtitle,
  answer_square,
  answer_type,
  expected_answer,
  moves,
  squares_touched,
  source,
  is_active,
  puzzle_kind,
  training_node_id
)
values
  (
    'drill-pin-knight',
    '8/8/4k3/3n4/2B5/8/8/4K3 w - - 0 1',
    '{"motif":"pin","attacker":"Bc4","target":"Nd5","pinned_to":"Ke6"}'::jsonb,
    'What square is the pinned knight on?',
    'e.g. a8',
    null,
    'd5',
    'square',
    'd5',
    '[]'::jsonb,
    '["c4","d5","e6"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    'node-4-1'
  ),
  (
    'drill-pin-bishop',
    '8/8/4k3/3n4/2B5/8/8/4K3 w - - 0 1',
    '{"motif":"pin","attacker":"Bc4","target":"Nd5","pinned_to":"Ke6"}'::jsonb,
    'What square is the pinning bishop on?',
    'e.g. a8',
    null,
    'c4',
    'square',
    'c4',
    '[]'::jsonb,
    '["c4","d5","e6"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    'node-4-1'
  ),
  (
    'drill-story-check',
    'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    '{"motif":"story_check"}'::jsonb,
    'Is the Black King in check?',
    'e.g. Yes',
    null,
    'e8',
    'yes-no',
    'no',
    '["e4","e5","Nf3","Nc6","Bc4","Nf6"]'::jsonb,
    '[]'::jsonb,
    'daily',
    true,
    'story_check',
    'node-5-1'
  ),
  (
    'drill-fork-knight',
    'k7/8/8/5r2/3N4/8/2q5/K7 w - - 0 1',
    '{"motif":"fork","attacker":"Nd4"}'::jsonb,
    'What square is the knight fork on?',
    'e.g. a8',
    null,
    'd4',
    'square',
    'd4',
    '[]'::jsonb,
    '["d4","c2","f5"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    'node-4-2'
  ),
  (
    'drill-skewer-rook',
    '4k3/8/3r4/8/8/3K4/3B4/8 w - - 0 1',
    '{"motif":"skewer","attacker":"Rd6","target":"Kd3"}'::jsonb,
    'What square is the White King on?',
    'e.g. a8',
    null,
    'd3',
    'square',
    'd3',
    '[]'::jsonb,
    '["d6","d3","d2"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-discovered-bishop',
    '4k3/6q1/8/8/3P4/8/1B6/4K3 w - - 0 1',
    '{"motif":"discovered_attack","attacker":"Bb2","target":"Qg7"}'::jsonb,
    'What square does the White Bishop attack from?',
    'e.g. a8',
    null,
    'b2',
    'square',
    'b2',
    '["d5"]'::jsonb,
    '["b2","g7","d5"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-hanging-king',
    '4k3/8/8/8/8/8/4r3/4K3 w - - 0 1',
    '{"motif":"hanging_piece","target":"Ke1"}'::jsonb,
    'The White King is in check — what square is it on?',
    'e.g. a8',
    null,
    'e1',
    'square',
    'e1',
    '[]'::jsonb,
    '["e1","e2"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-pin-rook-pawn',
    '4k3/4r3/8/8/8/8/4P3/4K3 w - - 0 1',
    '{"motif":"pin","attacker":"Re7","target":"e2","pinned_to":"Ke1"}'::jsonb,
    'What square is the pinned pawn on?',
    'e.g. a8',
    null,
    'e2',
    'square',
    'e2',
    '[]'::jsonb,
    '["e7","e2","e1"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    'node-4-1'
  ),
  (
    'drill-pin-relative-knight',
    '3qk3/8/5n2/6B1/8/8/8/4K3 w - - 0 1',
    '{"motif":"pin","attacker":"Bg5","target":"Nf6","pinned_to":"Qd8"}'::jsonb,
    'What square is the pinned knight on?',
    'e.g. a8',
    null,
    'f6',
    'square',
    'f6',
    '[]'::jsonb,
    '["g5","f6","d8"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-pin-bishop-diagonal',
    '4k3/8/2n5/1B6/8/8/8/4K3 w - - 0 1',
    '{"motif":"pin","attacker":"Bb5","target":"Nc6","pinned_to":"Ke8"}'::jsonb,
    'What square is the pinned knight on?',
    'e.g. a8',
    null,
    'c6',
    'square',
    'c6',
    '[]'::jsonb,
    '["b5","c6","e8"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-pin-rook-attacker',
    '4k3/4r3/8/8/8/8/4P3/4K3 w - - 0 1',
    '{"motif":"pin","attacker":"Re7","target":"e2","pinned_to":"Ke1"}'::jsonb,
    'What square is the pinning rook on?',
    'e.g. a8',
    null,
    'e7',
    'square',
    'e7',
    '[]'::jsonb,
    '["e7","e2","e1"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-pin-queen-behind',
    '3qk3/8/5n2/6B1/8/8/8/4K3 w - - 0 1',
    '{"motif":"pin","attacker":"Bg5","target":"Nf6","pinned_to":"Qd8"}'::jsonb,
    'What square is the Black Queen on?',
    'e.g. a8',
    null,
    'd8',
    'square',
    'd8',
    '[]'::jsonb,
    '["g5","f6","d8"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-pin-bishop-attacker',
    '4k3/8/2n5/1B6/8/8/8/4K3 w - - 0 1',
    '{"motif":"pin","attacker":"Bb5","target":"Nc6","pinned_to":"Ke8"}'::jsonb,
    'What square is the pinning bishop on?',
    'e.g. a8',
    null,
    'b5',
    'square',
    'b5',
    '[]'::jsonb,
    '["b5","c6","e8"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-pin-king-behind',
    '4k3/4r3/8/8/8/8/4P3/4K3 w - - 0 1',
    '{"motif":"pin","attacker":"Re7","target":"e2","pinned_to":"Ke1"}'::jsonb,
    'What square is the White King pinned to?',
    'e.g. a8',
    null,
    'e1',
    'square',
    'e1',
    '[]'::jsonb,
    '["e7","e2","e1"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-pin-bishop-f6',
    '4k3/8/5n2/4B3/8/8/8/4K3 w - - 0 1',
    '{"motif":"hanging_piece","attacker":"Be5","target":"Nf6"}'::jsonb,
    'What square is the undefended knight on?',
    'e.g. a8',
    null,
    'f6',
    'square',
    'f6',
    '[]'::jsonb,
    '["f6","e5"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-fork-royal-knight',
    '8/8/8/8/3N4/8/2q1k3/1K6 w - - 0 1',
    '{"motif":"fork","attacker":"Nd4","target":"Qc2"}'::jsonb,
    'What square is the knight fork on?',
    'e.g. a8',
    null,
    'd4',
    'square',
    'd4',
    '[]'::jsonb,
    '["d4","c2","e2"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    'node-4-2'
  ),
  (
    'drill-fork-pawn-e4',
    '8/8/8/3n1b2/4P3/8/8/4K2k w - - 0 1',
    '{"motif":"fork","attacker":"e4","target":"Nd5"}'::jsonb,
    'What square is the pawn fork on?',
    'e.g. a8',
    null,
    'e4',
    'square',
    'e4',
    '[]'::jsonb,
    '["e4","d5","f5"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-fork-queen-d5',
    '4k3/8/3b4/3r3r/4Q3/8/8/4K3 w - - 0 1',
    '{"motif":"fork","attacker":"Qe4","target":"Rd5"}'::jsonb,
    'What square is the queen fork on?',
    'e.g. a8',
    null,
    'e4',
    'square',
    'e4',
    '[]'::jsonb,
    '["e4","d5","e8"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-fork-queen-target',
    '4k3/8/3b4/3r3r/4Q3/8/8/4K3 w - - 0 1',
    '{"motif":"fork","attacker":"Qe4","target":"Rd5"}'::jsonb,
    'What square is one of the forked rooks on?',
    'e.g. a8',
    null,
    'd5',
    'square',
    'd5',
    '[]'::jsonb,
    '["e4","d5","e8"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-fork-knight-queen',
    'k7/8/8/8/3N4/8/2q5/K7 w - - 0 1',
    '{"motif":"hanging_piece","attacker":"Nd4","target":"Qc2"}'::jsonb,
    'What square is the forked queen on?',
    'e.g. a8',
    null,
    'c2',
    'square',
    'c2',
    '[]'::jsonb,
    '["c2","d4"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-fork-bishop-pair',
    '8/8/8/3n1b2/4P3/8/8/4K2k w - - 0 1',
    '{"motif":"fork","attacker":"e4","target":"Nd5"}'::jsonb,
    'What square is the forked knight on?',
    'e.g. a8',
    null,
    'd5',
    'square',
    'd5',
    '[]'::jsonb,
    '["e4","d5","f5"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-skewer-queen-behind',
    '4k3/8/8/3r4/8/3K4/8/3Q4 w - - 0 1',
    '{"motif":"skewer","attacker":"Rd5","target":"Kd3","square":"d1"}'::jsonb,
    'What square is the White King on?',
    'e.g. a8',
    null,
    'd3',
    'square',
    'd3',
    '[]'::jsonb,
    '["d5","d3","d1"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-skewer-bishop-rear',
    '4k3/8/3r4/8/8/3K4/3B4/8 w - - 0 1',
    '{"motif":"skewer","attacker":"Rd6","target":"Kd3","square":"d2"}'::jsonb,
    'What square is the skewered bishop on?',
    'e.g. a8',
    null,
    'd2',
    'square',
    'd2',
    '[]'::jsonb,
    '["d6","d3","d2"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-skewer-rook-attacker',
    '4k3/8/8/3r4/8/3K4/8/3Q4 w - - 0 1',
    '{"motif":"skewer","attacker":"Rd5","target":"Kd3","square":"d1"}'::jsonb,
    'What square is the skewering rook on?',
    'e.g. a8',
    null,
    'd5',
    'square',
    'd5',
    '[]'::jsonb,
    '["d5","d3","d1"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-hanging-queen-a4',
    '4k3/8/8/8/q7/8/8/R3K3 w - - 0 1',
    '{"motif":"hanging_piece","attacker":"Qa4","target":"Ra1"}'::jsonb,
    'What square is the undefended rook on?',
    'e.g. a8',
    null,
    'a1',
    'square',
    'a1',
    '[]'::jsonb,
    '["a1","a4"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    'node-4-3'
  ),
  (
    'drill-hanging-attacker-rook',
    '4k3/8/8/8/q7/8/8/R3K3 w - - 0 1',
    '{"motif":"hanging_piece","attacker":"Qa4","target":"Ra1"}'::jsonb,
    'What square is the attacking rook on?',
    'e.g. a8',
    null,
    'a1',
    'square',
    'a1',
    '[]'::jsonb,
    '["a1","a4"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-fork-queen-f5',
    '4k3/8/4N3/5q2/4P1N1/8/8/4K3 w - - 0 1',
    '{"motif":"fork","attacker":"Qf5","target":"e4"}'::jsonb,
    'What square is the queen fork on?',
    'e.g. a8',
    null,
    'f5',
    'square',
    'f5',
    '[]'::jsonb,
    '["f5","e4","g4","e6"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-disc-rook-check',
    '7k/8/8/8/8/6p1/7P/2K4R w - - 0 1',
    '{"motif":"discovered_attack","attacker":"Rh1","target":"Kh8","square":"g3"}'::jsonb,
    'What square does the White Rook attack from?',
    'e.g. a8',
    null,
    'h1',
    'square',
    'h1',
    '["hxg3"]'::jsonb,
    '["h1","h8","g3"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-disc-knight-check',
    '7k/8/8/8/8/8/7N/2K4R w - - 0 1',
    '{"motif":"discovered_attack","attacker":"Rh1","target":"Kh8","square":"g4"}'::jsonb,
    'What square does the White Rook attack from?',
    'e.g. a8',
    null,
    'h1',
    'square',
    'h1',
    '["Ng4"]'::jsonb,
    '["h1","h8","g4"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-disc-queen-rook',
    'r3k3/8/8/8/R7/8/8/Q3K3 w - - 0 1',
    '{"motif":"discovered_attack","attacker":"Qa1","target":"Ra8","square":"h4"}'::jsonb,
    'What square does the White Queen attack from?',
    'e.g. a8',
    null,
    'a1',
    'square',
    'a1',
    '["Rh4"]'::jsonb,
    '["a1","a8","h4"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-disc-rook-attacker',
    '7k/8/8/8/8/6p1/7P/2K4R w - - 0 1',
    '{"motif":"discovered_attack","attacker":"Rh1","target":"Kh8","square":"g3"}'::jsonb,
    'What square does the White Rook attack from?',
    'e.g. a8',
    null,
    'h1',
    'square',
    'h1',
    '["hxg3"]'::jsonb,
    '["h1","h8","g3"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-story-check-yes',
    'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    '{"motif":"story_check"}'::jsonb,
    'Is the Black King in check?',
    'e.g. Yes',
    null,
    'e8',
    'yes-no',
    'yes',
    '["e4","e5","Qh5","Nc6","Bc4","Nf6","Qxf7+"]'::jsonb,
    '[]'::jsonb,
    'daily',
    true,
    'story_check',
    'node-5-1'
  ),
  (
    'drill-story-check-white-no',
    'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    '{"motif":"story_check"}'::jsonb,
    'Is the White King in check?',
    'e.g. Yes',
    null,
    'e1',
    'yes-no',
    'no',
    '["d4","d5","c4","e6","Nc3","Nf6"]'::jsonb,
    '[]'::jsonb,
    'daily',
    true,
    'story_check',
    'node-5-1'
  ),
  (
    'drill-story-check-scholar',
    'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    '{"motif":"story_check"}'::jsonb,
    'Is the Black King in check?',
    'e.g. Yes',
    null,
    'e8',
    'yes-no',
    'no',
    '["e4","e5","Bc4","Nc6","Qh5"]'::jsonb,
    '[]'::jsonb,
    'daily',
    true,
    'story_check',
    null
  ),
  (
    'drill-story-check-pin',
    'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    '{"motif":"story_check"}'::jsonb,
    'Is the White King in check?',
    'e.g. Yes',
    null,
    'e1',
    'yes-no',
    'no',
    '["e4","e5","Nf3","d6","d4","Bg4"]'::jsonb,
    '[]'::jsonb,
    'daily',
    true,
    'story_check',
    null
  ),
  (
    'drill-story-memorize-fork',
    '4k3/8/8/5r2/3N4/8/2q5/K7 w - - 0 1',
    '{"motif":"hanging_piece","attacker":"Qc2","target":"Nf5"}'::jsonb,
    'What square is the undefended knight on?',
    'e.g. a8',
    null,
    'f5',
    'square',
    'f5',
    '["Nxf5"]'::jsonb,
    '["f5","c2"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-fork-bishop-pair-b',
    '8/8/8/3b3b/4N3/8/8/4K2k w - - 0 1',
    '{"motif":"hanging_piece","attacker":"Bd5","target":"Ne4"}'::jsonb,
    'What square is the undefended knight on?',
    'e.g. a8',
    null,
    'e4',
    'square',
    'e4',
    '[]'::jsonb,
    '["e4","d5"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-skewer-bishop-diagonal',
    '4k3/8/8/8/8/3K4/3B4/4r3 w - - 0 1',
    '{"motif":"hanging_piece","attacker":"Bd2","target":"Re1"}'::jsonb,
    'What square is the undefended rook on?',
    'e.g. a8',
    null,
    'e1',
    'square',
    'e1',
    '[]'::jsonb,
    '["e1","d2"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-hanging-queen-a7',
    '4k3/q7/8/8/8/8/8/R3K3 w - - 0 1',
    '{"motif":"hanging_piece","attacker":"Qa7","target":"Ra1"}'::jsonb,
    'What square is the undefended rook on?',
    'e.g. a8',
    null,
    'a1',
    'square',
    'a1',
    '[]'::jsonb,
    '["a1","a7"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    'node-4-3'
  ),
  (
    'drill-pin-knight-c3',
    '4k3/8/8/8/2n5/1B6/8/4K3 w - - 0 1',
    '{"motif":"hanging_piece","attacker":"Bb3","target":"Nc4"}'::jsonb,
    'What square is the undefended knight on?',
    'e.g. a8',
    null,
    'c4',
    'square',
    'c4',
    '[]'::jsonb,
    '["c4","b3"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-fork-knight-back',
    '8/8/8/8/1N6/8/2q1k2r/K7 w - - 0 1',
    '{"motif":"hanging_piece","attacker":"Nb4","target":"Qc2"}'::jsonb,
    'What square is the undefended queen on?',
    'e.g. a8',
    null,
    'c2',
    'square',
    'c2',
    '[]'::jsonb,
    '["c2","b4"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-story-italian',
    'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    '{"motif":"story_check"}'::jsonb,
    'Is the Black King in check?',
    'e.g. Yes',
    null,
    'e8',
    'yes-no',
    'no',
    '["e4","e5","Nf3","Nc6","Bc4","Bc5"]'::jsonb,
    '[]'::jsonb,
    'daily',
    true,
    'story_check',
    null
  ),
  (
    'drill-story-disc-prep',
    'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    '{"motif":"story_check"}'::jsonb,
    'Is the Black King in check?',
    'e.g. Yes',
    null,
    'e8',
    'yes-no',
    'no',
    '["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5"]'::jsonb,
    '[]'::jsonb,
    'daily',
    true,
    'story_check',
    null
  ),
  (
    'drill-disc-pawn-queen',
    '4k3/6q1/8/8/3P4/8/1B6/4K3 w - - 0 1',
    '{"motif":"discovered_attack","attacker":"Bb2","target":"Qg7","square":"d5"}'::jsonb,
    'What square is the discovered attack target on?',
    'e.g. a8',
    null,
    'g7',
    'square',
    'g7',
    '["d5"]'::jsonb,
    '["b2","g7","d5"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-pin-attacker-c4',
    '8/8/4k3/3n4/2B5/8/8/4K3 w - - 0 1',
    '{"motif":"pin","attacker":"Bc4","target":"Nd5","pinned_to":"Ke6"}'::jsonb,
    'What square is the pinning bishop on?',
    'e.g. a8',
    null,
    'c4',
    'square',
    'c4',
    '[]'::jsonb,
    '["c4","d5","e6"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-hanging-rook-e3',
    '4k3/8/8/8/8/4r3/8/4K3 w - - 0 1',
    '{"motif":"hanging_piece","attacker":"Re3","target":"Ke1"}'::jsonb,
    'The White King is in check — what square is it on?',
    'e.g. a8',
    null,
    'e1',
    'square',
    'e1',
    '[]'::jsonb,
    '["e1","e3"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-fork-knight-dual',
    'k7/8/8/8/3N4/8/2q1r3/K7 w - - 0 1',
    '{"motif":"fork","attacker":"Nd4","target":"Qc2"}'::jsonb,
    'What square is the knight fork on?',
    'e.g. a8',
    null,
    'd4',
    'square',
    'd4',
    '[]'::jsonb,
    '["d4","c2","e2"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    'node-4-2'
  ),
  (
    'drill-pin-queen-d8',
    '3qk3/8/5n2/6B1/8/8/8/4K3 w - - 0 1',
    '{"motif":"pin","attacker":"Bg5","target":"Nf6","pinned_to":"Qd8"}'::jsonb,
    'What square is the pinned piece on?',
    'e.g. a8',
    null,
    'f6',
    'square',
    'f6',
    '[]'::jsonb,
    '["g5","f6","d8"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-story-london',
    'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    '{"motif":"story_check"}'::jsonb,
    'Is the Black King in check?',
    'e.g. Yes',
    null,
    'e8',
    'yes-no',
    'no',
    '["d4","d5","Bf4","Nf6","e3","e6"]'::jsonb,
    '[]'::jsonb,
    'daily',
    true,
    'story_check',
    null
  ),
  (
    'drill-story-check-white-yes',
    'rnbqkbnr/pppp1ppp/8/4p3/6Pq/5P2/PPPPP2P/RNBQKBNR w KQkq - 0 1',
    '{"motif":"story_check"}'::jsonb,
    'Is the White King in check?',
    'e.g. Yes',
    null,
    'e1',
    'yes-no',
    'yes',
    '[]'::jsonb,
    '[]'::jsonb,
    'daily',
    true,
    'story_check',
    null
  ),
  (
    'drill-pin-queen-file',
    '4k3/8/8/8/4q3/8/4P3/4K3 w - - 0 1',
    '{"motif":"pin","attacker":"Qe4","target":"e2","pinned_to":"Ke1"}'::jsonb,
    'What square is the pinned pawn on?',
    'e.g. a8',
    null,
    'e2',
    'square',
    'e2',
    '[]'::jsonb,
    '["e4","e2","e1"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  ),
  (
    'drill-hanging-knight-f6',
    '4k3/8/5n2/8/5R2/8/8/4K3 w - - 0 1',
    '{"motif":"hanging_piece","attacker":"Rf4","target":"Nf6"}'::jsonb,
    'What square is the undefended knight on?',
    'e.g. a8',
    null,
    'f6',
    'square',
    'f6',
    '[]'::jsonb,
    '["f6","f4"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    'node-4-3'
  ),
  (
    'drill-story-memorize-check',
    '4k3/8/4R3/8/8/8/8/4K3 w - - 0 1',
    '{"motif":"story_check"}'::jsonb,
    'Is the Black King in check?',
    'e.g. Yes',
    null,
    'e8',
    'yes-no',
    'yes',
    '["Re7+"]'::jsonb,
    '[]'::jsonb,
    'daily',
    true,
    'story_check',
    null
  ),
  (
    'drill-pin-rook-backrank',
    '4k3/8/8/8/8/4r3/4P3/4K3 w - - 0 1',
    '{"motif":"pin","attacker":"Re3","target":"e2","pinned_to":"Ke1"}'::jsonb,
    'What square is the pinned pawn on?',
    'e.g. a8',
    null,
    'e2',
    'square',
    'e2',
    '[]'::jsonb,
    '["e3","e2","e1"]'::jsonb,
    'daily',
    true,
    'functional_geometry',
    null
  )
on conflict (slug) do update
set
  fen = excluded.fen,
  motif_json = excluded.motif_json,
  nlp_prompt = excluded.nlp_prompt,
  input_placeholder = excluded.input_placeholder,
  subtitle = excluded.subtitle,
  answer_square = excluded.answer_square,
  answer_type = excluded.answer_type,
  expected_answer = excluded.expected_answer,
  moves = excluded.moves,
  squares_touched = excluded.squares_touched,
  source = excluded.source,
  is_active = excluded.is_active,
  puzzle_kind = excluded.puzzle_kind,
  training_node_id = excluded.training_node_id,
  updated_at = now();

-- Authoring audio (story) puzzles — rows with a non-empty moves[] array:
--
--   Pattern A — narration only (blank screen):
--     fen   = standard start position
--     moves = legal SAN sequence from the start (3–5 moves reads well)
--     The app skips the board and reads the moves aloud. Works because
--     every player knows the starting position.
--
--   Pattern B — memorize, then narrate:
--     fen   = any custom position (the BASE position, before moves)
--     moves = short legal SAN continuation (1–2 plies)
--     The app shows the base board for 5s, hides it, reads the moves,
--     then asks the question about the resulting position.
--
--   Rules:
--   - moves[] must be legal from fen (validated by chess-core fixtures).
--   - subtitle must NOT mention the moves — it shows during memorize.
--   - expected_answer refers to the position AFTER moves are applied.
--   - Peek shows the BASE position, never the post-move position.
--   - Mirror each row in packages/chess-core/src/motifs/fixtures/
--     puzzle-bank-fixtures.json and run `npm run validate:puzzles`.
